# Generated by Django 3.2.8 on 2021-10-21 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211019_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 17, 3, 56, 935160, tzinfo=utc)),
        ),
    ]
