# Generated by Django 3.2.8 on 2021-10-25 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211024_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 27, 15, 29, 57, 342796, tzinfo=utc), null=True),
        ),
    ]
