# Generated by Django 3.2.8 on 2021-10-28 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_activation_key_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 30, 17, 53, 50, 985344, tzinfo=utc), null=True),
        ),
    ]
